### PR TITLE
Get device and service groups

### PR DESCRIPTION
**Pull request by shurl**
Added functions and tests to get device and service group names. 

@jonathan-s can you review please?

### CODE REVIEW

**Comment by jonathan-s** [comment]
Perhaps you can add functional tests for getting device and service group names as well?

**Comment by shurl** [comment]
I can certainly give it a go :)

**Comment by shurl** [comment]
@jonathan-s are these suitable?

**Comment by jonathan-s** [comment]
:+1:

**Comment by jonathan-s** [comment]
If you give it a new tag with a higher version number it will automagically be pushed to the packagist!

**Pull request merged**
